name: manually-triggering-docker-image-build-and-push

on: push

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout to main branch and get project version
      uses: actions/checkout@main
      env:
        VERSION: $(cat package.json | grep '"version":' | awk '{print $2}' | tr -d '",')
    - 
      name: Navigate to docker directory
      run: |
        cd docker
        echo "docker image tag: ${VERSION}"
    -
      name: Login to DockerHub
      run: |
        echo "docker image tag: ${VERSION}"
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Build docker image
      run: docker build -t jhipster-generator-dotnetcore:${VERSION} -t jhipster-generator-dotnetcore:latest .
    -
      name: Tag local image created to jhipster generator repository
      run: |
        docker tag jhipster-generator-dotnetcore:${VERSION} ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${VERSION}
        docker tag jhipster-generator-dotnetcore:latest ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:latest
    -
      name: Push docker image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${VERSION}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:latest
    -
      name: Logout of DockerHub
      run: docker logout



  # if: github.event.pull_request.merged