name: docker image push triggered on push event

on: push

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout to main branch
      uses: actions/checkout@main
    -
      name: Get project version
      id: jhipster_generator
      run: echo "::set-output name=version::$(cat package.json | grep '"version":' | awk '{print $2}' | tr -d '",')"
    - 
      name: Navigate to docker directory
      run: cd docker
    -
      name: Login to DockerHub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Build docker image
      run: |
        docker build -t jhipster-generator-dotnetcore:${{ steps.jhipster_generator.outputs.version }} -t jhipster-generator-dotnetcore:latest .
    -
      name: Tag local image to jhipster generator registry and push it to docker hub
      run: |
        VERSION=${{ steps.jhipster_generator.outputs.version }}
        USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
        REPOSITORY=${{ secrets.DOCKERHUB_REPOSITORY }}
        docker tag jhipster-generator-dotnetcore:$VERSION $USERNAME/$REPOSITORY:$VERSION
        docker tag jhipster-generator-dotnetcore:latest $USERNAME/$REPOSITORY:latest
        docker push $USERNAME/$REPOSITORY:$VERSION
        docker push $USERNAME/$REPOSITORY:latest
    -
      name: Logout of DockerHub
      run: docker logout



  # if: github.event.pull_request.merged