name: My First Manual Workflow
on: [workflow_dispatch]
jobs:
  example:
    name: Example Job
    runs-on: ubuntu-latest
    steps:
      - name: checkout actions
        uses: actions/checkout@v2
      - name: print something
        run: echo "triggered sucessfully"
